### ISSUE TITLE
GitHub Project name is incorrect

### ISSUE THREAD

**Issue by noobanidus** [quat1024/carvemelon#1]
While technically you can "carve melon", if you're talking about melons in the abstract ("I eat melon all the time", "I carve melon all the time"), it doesn't come across as though an imperative ("Go forth, carve melon!") and on its own cannot act as an adjective. In this instance, you'd need the past participle ("carved") for it to make any sense. Given that there are more than 1 melon, "CarvedMelons" would be most appropriate.

This would bring the project in line with your CurseForge page.

---

Trolling aside, you should totally port this to 1.12.2 where it might actually see usage.

**Comment by quat1024** [comment]
> title

it's the name of the folder on my computer

> 1.12.2

mayb
