### ISSUE TITLE
Mixin related crash on game load

### ISSUE THREAD

**Issue by Shnupbups** [quat1024/carvemelon#2]
1.14 Pre5, Fabric API 0.2.7 build126, Loader 0.4.1 build126

Relevant crash log portion: https://paste.ee/r/MLx1r

**Comment by quat1024** [comment]
Wot :confused:

**Comment by quat1024** [comment]
Let me guess, you don't use Windows? I think it was a casing issue

**Comment by Shnupbups** [comment]
No, I do use Windows. Windows 10.

**Comment by quat1024** [comment]
![oof](https://user-images.githubusercontent.com/2068021/56465235-b94d3f80-63c7-11e9-8a5a-4e607ec51d12.png)

**Comment by quat1024** [comment]
Try 1.1.1, on curse now @ https://minecraft.curseforge.com/projects/carved-melons/files/2701801

This was a genuine "works for me" situation so... idk!
